package solution.peer.commPackage;

public enum PackageType {

    START, PING, PING_RESPONSE, WALK, LEAVE_WALK, COUNT_WALK, BROADCAST, UPDATE_FINGER_TABLE_BROADCAST, UPDATE_VISIBLENODES_BROADCAST, COLLECT_ALL_NODES_WALK, UPDATE_RESULT_BROADCAST, STEAL_JOB, TAKE_JOB,
    BOOTSTRAP_JOIN, BOOTSTRAP_LEAVE, REQUEST_TOKEN, SEND_TOKEN, UPDATE_RN_BROADCAST,
    NEW_NODE_REORGANIZATION_REQUEST, SET_SUCCESSOR

}
