package solution.peer.commPackage;

public enum PackageType {

    START, PING, PING_RESPONSE, BROADCAST, BROADCAST_LEAVE, COUNT,
    BOOTSTRAP_JOIN, BOOTSTRAP_LEAVE,
    NEW_NODE_REORGANIZATION_REQUEST, SET_SUCCESSOR

}
